version: "3.9"

services:
  client:
    build:
      context: ./client
    image: jm-premium-client:latest
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - jm-premium-network
    environment:
      - HOST=0.0.0.0

  server:
    build:
      context: ./server
    image: jm-premium-server:latest
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - ./server/gcp-key.json:/secrets/key.json 
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/key.json
      - PYTHONUNBUFFERED=1
    networks:
      - jm-premium-network

networks:
  jm-premium-network:
    driver: bridge
