version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - jm-premium-network
    environment:
      - HOST=0.0.0.0

  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    networks:
      - jm-premium-network

networks:
  jm-premium-network:
    driver: bridge
