version: "3.9"

services:
  client:
    build:
      context: ./client
    image: jm-premium-client:latest
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - jm-premium-network
    environment:
      - HOST=0.0.0.0

  server:
    build:
      context: ./server
    image: jm-premium-server:latest
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - ./server/gcp-key.json:/secrets/key.json 
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/key.json
      - PYTHONUNBUFFERED=1
      - SQLALCHEMY_DATABASE_URI=postgresql://rootuser:rootpass@db:5432/jmpremium_dev
    depends_on:
      - db
    networks:
      - jm-premium-network

  db:
    image: postgres:15
    container_name: local-postgres
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: jmpremium_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jm-premium-network

networks:
  jm-premium-network:
    driver: bridge

volumes:
  postgres_data:
