"""Add benefits, ingredients, and instructions to product model

Revision ID: 2d8d1ce4eb50
Revises: 70fb38c56e26
Create Date: 2025-05-10 22:39:52.914935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8d1ce4eb50'
down_revision = '70fb38c56e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefits', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('instructions')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('benefits')

    # ### end Alembic commands ###
