"""Remove profile picture from user model

Revision ID: 7dc2964a203e
Revises: 87e067da7157
Create Date: 2025-05-04 01:35:34.211503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc2964a203e'
down_revision = '87e067da7157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
