"""Update to use V3 Xendit API

Revision ID: 80129da136be
Revises: f4d78e20bf7b
Create Date: 2025-07-14 01:03:38.447274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80129da136be'
down_revision = 'f4d78e20bf7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('checkout_url')
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('checkout_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
