"""Update payment model

Revision ID: a7ec8c948bb7
Revises: 2d8d1ce4eb50
Create Date: 2025-07-13 00:28:24.691780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ec8c948bb7'
down_revision = '2d8d1ce4eb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('xendit_invoice_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('invoice_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('invoice_url')
        batch_op.drop_column('xendit_invoice_id')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
