"""Remove primary image

Revision ID: e991d3af8ebe
Revises: 41932f38058e
Create Date: 2025-05-08 21:53:11.472762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e991d3af8ebe'
down_revision = '41932f38058e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
