"""Update fields to for Xendit Payment Requests API

Revision ID: f4d78e20bf7b
Revises: a7ec8c948bb7
Create Date: 2025-07-13 18:33:26.457245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d78e20bf7b'
down_revision = 'a7ec8c948bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('xendit_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('checkout_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('xendit_invoice_id')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('invoice_url')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('xendit_invoice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('checkout_url')
        batch_op.drop_column('xendit_id')
        batch_op.drop_column('reference_id')

    # ### end Alembic commands ###
