"""Change depth to length

Revision ID: fdda36d3b170
Revises: 8bf8f3af87e5
Create Date: 2025-05-08 19:47:42.746076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdda36d3b170'
down_revision = '8bf8f3af87e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('depth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depth', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('length')

    # ### end Alembic commands ###
